// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timelogger.Infrastructure.Data;

namespace Timelogger.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("Timelogger.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Timelogger.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FreelancerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Timelogger.Domain.Entities.WorkEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("WorkEntries");
                });

            modelBuilder.Entity("Timelogger.Domain.Entities.Client", b =>
                {
                    b.OwnsOne("Timelogger.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnName("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnName("Country")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnName("Street")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnName("ZipCode")
                                .HasColumnType("TEXT");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });

                    b.OwnsOne("Timelogger.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("ClientId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnName("FirstName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnName("LastName")
                                .HasColumnType("TEXT");

                            b1.HasKey("ClientId");

                            b1.ToTable("Clients");

                            b1.WithOwner()
                                .HasForeignKey("ClientId");
                        });
                });

            modelBuilder.Entity("Timelogger.Domain.Entities.Project", b =>
                {
                    b.HasOne("Timelogger.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Timelogger.Domain.ValueObjects.Audit", "Audit", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnName("CreatedBy")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnName("CreatedDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnName("ModifiedBy")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedDate")
                                .HasColumnName("ModifiedDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });
                });

            modelBuilder.Entity("Timelogger.Domain.Entities.WorkEntry", b =>
                {
                    b.HasOne("Timelogger.Domain.Entities.Project", null)
                        .WithMany("WorkEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Timelogger.Domain.ValueObjects.Audit", "Audit", b1 =>
                        {
                            b1.Property<int>("WorkEntryId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CreatedBy")
                                .IsRequired()
                                .HasColumnName("CreatedBy")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnName("CreatedDate")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnName("ModifiedBy")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("ModifiedDate")
                                .HasColumnName("ModifiedDate")
                                .HasColumnType("TEXT");

                            b1.HasKey("WorkEntryId");

                            b1.ToTable("WorkEntries");

                            b1.WithOwner()
                                .HasForeignKey("WorkEntryId");
                        });

                    b.OwnsOne("Timelogger.Domain.ValueObjects.WorkHours", "Hours", b1 =>
                        {
                            b1.Property<int>("WorkEntryId")
                                .HasColumnType("INTEGER");

                            b1.Property<decimal>("Value")
                                .HasColumnName("WorkHours")
                                .HasColumnType("TEXT");

                            b1.HasKey("WorkEntryId");

                            b1.ToTable("WorkEntries");

                            b1.WithOwner()
                                .HasForeignKey("WorkEntryId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
